import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import {
    Plus,
    Briefcase
} from 'lucide-react';
import companiesService from '../../services/companiesService';

export default function AddCompany() {
    const navigate = useNavigate();
    const fileInputRef = useRef(null);

    // UI State
    const [isFormOpen, setIsFormOpen] = useState(false);

    // Form State - Restoring fields from old CompanyForm
    const [formData, setFormData] = useState({
        name: '',
        email: '', // Company Email
        ownerName: '',
        password: '',
        phone: '',
        address: '',
        logo: null
    });

    // Derived fields automatically handled in service: 
    // code (auto-generated by backend based on name)

    const [showPassword, setShowPassword] = useState(false);
    const [loading, setLoading] = useState(false);
    const [errors, setErrors] = useState({});

    // Default modules hidden from UI
    const defaultModules = ['hr', 'leave', 'attendance', 'payroll', 'recruitment', 'performance'];

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
        if (errors[name]) setErrors(prev => ({ ...prev, [name]: '' }));
    };

    const handleFileChange = (e) => {
        const file = e.target.files[0];
        setFormData(prev => ({ ...prev, logo: file }));
    };

    const validate = () => {
        const errs = {};
        if (!formData.name) errs.name = 'Required';
        if (!formData.email) errs.email = 'Required';
        if (!formData.ownerName) errs.ownerName = 'Required';
        if (!formData.password) errs.password = 'Required';
        // Phone/Address optional depending on strictness, usually required
        // if (!formData.phone) errs.phone = 'Required'; 

        setErrors(errs);
        return Object.keys(errs).length === 0;
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        if (!validate()) return;

        setLoading(true);
        try {
            // 1. Upload Logo if exists
            let logoUrl = '';
            if (formData.logo) {
                try {
                    const upRes = await companiesService.uploadLogo(formData.logo);
                    logoUrl = upRes.url || upRes.path || '';
                } catch (e) { console.warn('Logo upload excluded'); }
            }

            // 2. Prepare Payload (Mapping back to what backend expects)
            // Backend Controller expects: { name, emailDomain, meta: { primaryEmail, ownerName, phone, address, logo, adminPassword } }
            // Note: 'code' is auto-generated by backend if not provided, or we can slugify validation.
            // Using backend auto-generation is safer if logic exists there.

            const payload = {
                name: formData.name,
                // code: Auto-generated or simple slug
                code: formData.name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 10),
                status: 'active',
                modules: defaultModules,
                meta: {
                    primaryEmail: formData.email, // Using Company Email as Primary
                    email: formData.email,        // Admin Email same as Primary for simplicity or user prompt
                    ownerName: formData.ownerName,
                    phone: formData.phone,
                    address: formData.address,
                    adminPassword: formData.password,
                    logo: logoUrl
                }
            };

            await companiesService.createCompany(payload);
            navigate('/psa/companies');

        } catch (error) {
            console.error(error);
            alert('Failed to create company. Check console.');
        } finally {
            setLoading(false);
        }
    };

    // 1. LANDING VIEW
    if (!isFormOpen) {
        return (
            <div className="min-h-[80vh] flex flex-col items-center justify-center p-4 font-sans">
                <div className="bg-white p-12 rounded-3xl shadow-sm border border-gray-100 text-center max-w-lg w-full">
                    <div className="w-20 h-20 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center mx-auto mb-6">
                        <Briefcase size={36} />
                    </div>
                    <h2 className="text-2xl font-bold text-gray-900 mb-2">Companies Management</h2>
                    <p className="text-gray-500 mb-8">Onboard a new client organization.</p>

                    <button
                        onClick={() => setIsFormOpen(true)}
                        className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white text-lg font-semibold rounded-2xl shadow-lg shadow-blue-200 transition-all hover:-translate-y-1 active:scale-95 flex items-center justify-center gap-3"
                    >
                        <Plus size={24} />
                        Add New Company
                    </button>

                    <button onClick={() => navigate('/psa/companies')} className="mt-6 text-gray-400 hover:text-blue-600 text-sm font-medium">
                        View Companies List
                    </button>
                </div>
            </div>
        );
    }

    // 2. FORM VIEW - Matching Old Fields Structure
    return (
        <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6 font-sans">
            <div className="bg-white rounded-xl shadow-lg w-full max-w-4xl p-8">
                <h2 className="text-xl font-bold text-gray-800 mb-6">Create Company</h2>

                <form onSubmit={handleSubmit} className="space-y-5">

                    {/* Company Name */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Company Name</label>
                        <input
                            type="text"
                            name="name"
                            value={formData.name}
                            onChange={handleInputChange}
                            className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                        />
                        {errors.name && <p className="text-xs text-red-500 mt-1">{errors.name}</p>}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                        {/* Company Email */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Company Email</label>
                            <input
                                type="email"
                                name="email"
                                value={formData.email}
                                onChange={handleInputChange}
                                className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                            />
                            {errors.email && <p className="text-xs text-red-500 mt-1">{errors.email}</p>}
                        </div>

                        {/* Owner Name */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Owner Name</label>
                            <input
                                type="text"
                                name="ownerName"
                                value={formData.ownerName}
                                onChange={handleInputChange}
                                className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                            />
                            {errors.ownerName && <p className="text-xs text-red-500 mt-1">{errors.ownerName}</p>}
                        </div>

                        {/* Password */}
                        <div className="relative">
                            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                            <input
                                type={showPassword ? "text" : "password"}
                                name="password"
                                value={formData.password}
                                onChange={handleInputChange}
                                className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                            />
                            <button
                                type="button"
                                onClick={() => setShowPassword(!showPassword)}
                                className="absolute right-3 top-8 text-xs text-gray-500 hover:text-blue-600"
                            >
                                {showPassword ? 'Hide' : 'Show'}
                            </button>
                            {errors.password && <p className="text-xs text-red-500 mt-1">{errors.password}</p>}
                        </div>

                        {/* Phone */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                            <input
                                type="text"
                                name="phone"
                                value={formData.phone}
                                onChange={handleInputChange}
                                className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                            />
                        </div>
                    </div>

                    {/* Address */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Address</label>
                        <input
                            type="text"
                            name="address"
                            value={formData.address}
                            onChange={handleInputChange}
                            className="w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:border-blue-500"
                        />
                    </div>

                    {/* File Upload (Simple) */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Company Logo</label>
                        <div className="flex items-center gap-2">
                            <button
                                type="button"
                                onClick={() => fileInputRef.current?.click()}
                                className="px-3 py-1.5 border border-gray-300 rounded bg-gray-50 text-sm hover:bg-gray-100"
                            >
                                Choose File
                            </button>
                            <span className="text-sm text-gray-500">{formData.logo ? formData.logo.name : 'No file chosen'}</span>
                            <input type="file" ref={fileInputRef} className="hidden" accept="image/*" onChange={handleFileChange} />
                        </div>
                    </div>

                    {/* Footer Buttons */}
                    <div className="flex justify-end gap-3 mt-8 pt-4 border-t border-gray-100">
                        <button
                            type="button"
                            onClick={() => setIsFormOpen(false)}
                            className="px-6 py-2 border border-gray-200 rounded text-gray-600 hover:bg-gray-50 transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            disabled={loading}
                            className="px-6 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
                        >
                            {loading ? 'Saving...' : 'Save'}
                        </button>
                    </div>

                </form>
            </div>
        </div>
    );
}
